[package]
name = "windows-cat"
version = "1.0.2"
edition = "2021"
description = "unix cat command for windows"
readme = "README.md"
repository = "https://github.com/tralwdwd/windows-cat"
license = "MIT"

[dependencies]
clap = "4.5.20"

[[bin]]
name = "cat"
path = "src/main.rs"