name: Repo sync GitHub -> Codeberg
on:
  push:
    branches:
    - '**'

jobs:
  codeberg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: spyoungtech/mirror-action@v0.7.0
        with:
          REMOTE: "https://codeberg.org/tralwdwd/windows-cat.git"
          GIT_USERNAME: tralwdwd
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
